version: '3.9'  # Update the version to 3.9 to avoid the obsolete warning
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  celery:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
    command: celery -A tasks worker --loglevel=info
  celery-beat:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
    command: celery -A tasks beat --loglevel=info
